cart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from portfolio import settings
from .views import *

urlpatterns = [
    path('', cart_summary, name='cart_summary'),
    path('add/', cart_add, name='cart_add'),
    # path('delete/', views.cart_delete, name='cart_delete'),
    # path('update/', views.cart_update, name='cart_update'),

]

portfolio/urls.py
# from django.contrib import admin
from django.contrib import admin
# from baton.autodiscover import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from shop.api import *
from shop.views import *
from feedback.views import contact
from app_loging.views import *

from portfolio.views import *
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    #reset_password_test
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
          name ='password_reset_confirm'),
    path('reset_password/', auth_views.PasswordResetView.as_view(),
         name ='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(),
         name ='password_reset_done'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(),
         name ='password_reset_complete'),
    #base
    path('', base, name='base'),
    #админка
    path('admin/', admin.site.urls),
    #auth
    path('registration/', RegisterUser.as_view(), name='registration'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    #projects
    path('projects/', projects, name='projects'),
    path('contact_form/', contact, name='contact_form'),
    path('lk/', lk, name='lk'),
    path('', include('social_django.urls', namespace='social')),
    #shop
    path('shop/', index, name='shop'),
    path('category/', category_list, name='category'),
    path('category/<title>/', product_list_view, name='product_list_view'),
    path('product/<title>/', product_view, name='product_view'),
    path('review/<title>/', add_review, name='add_review'),
    # path('add_cat/', add_category, name='add_category'),
    path('cart/', include('cart.urls')),
    ####API methods#########
    path('api/v1/projects/', ProjectsView.as_view(), name='api_projects'),
    path('api/v1/products/', ProductsView.as_view(), name='api_projects'),
    path('api/v1/categories/', CategoriesView.as_view(), name='api_projects'),
    ####API AUTH methods#########
      path('api/v1/drf-auth/', include('rest_framework.urls')),
      path('api/v1/auth/', include('djoser.urls')),
    path('api/v1/registration/', RegisterAccount.as_view(), name='api_reg'),
    path('api/v1/confirm/', ConfirmAccount.as_view(), name='api_conf'),
    path('api/v1/contact/', ContactView.as_view(), name='api_contact'),
    path('api/v1/details/', AccountDetails.as_view(), name='api_details'),
    path('api/v1/login/', LoginAccount.as_view(), name='api_login'),
    path('api/v1/order/', OrderView.as_view(), name='api_order'),
    path('api/v1/cart/', CartView.as_view(), name='api_cart'),
    #оптимизиция_не работает
    # path('silk/', include('silk.urls', namespace='silk'))
    #DRF
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.utils.safestring import mark_safe

from app_loging.models import User

STATUS_CHOISE = (
    ('в процессе', 'Обработка'),
    ('в доставке', 'В доставке'),
    ('доставлено', 'Доставлено'),
)

STATUS = (
    ('черновик', 'Черновик'),
    ('недоступно', 'Недоступно'),
    ('отклонено', 'Отклонено'),
    ('опубликовано', 'Опубликовано'),
)

RATING = (
    (1, '⭐✩✩✩✩'),
    (2, '⭐⭐✩✩✩'),
    (3, '⭐⭐⭐✩✩'),
    (4, '⭐⭐⭐⭐✩'),
    (5, '⭐⭐⭐⭐⭐'),
)


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class Category(models.Model):
    title = models.CharField(max_length=500, default='The Best Category')
    image = models.ImageField(upload_to='category', default='category.jpg')

    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'

    def category_image(self):
        return mark_safe('<img src="%s" width = "50" height = "50">' % (self.image.url))

    def __str__(self):
        return self.title


class Vendor(models.Model):
    title = models.CharField(max_length=500, default='The Best Vendor')
    image = models.ImageField(upload_to=user_directory_path, default='vendor.jpg')
    description = models.TextField(null=True)
    available = models.BooleanField(default=False)

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = 'Продавцы'
        verbose_name = 'Продавец'

    def vendor_image(self):
        return mark_safe('<img src="%s" width = "50" height = "50">' % (self.image.url))

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=500, default='The Best Product')
    image = models.ImageField(upload_to=user_directory_path, default='product.jpg')
    description = models.TextField(null=True)
    price = models.IntegerField(default='199')
    old_price = models.IntegerField(default='299')
    product_status = models.CharField(choices=STATUS, max_length=100, default='черновик')
    feachured = models.BooleanField(default=False, verbose_name='Опубликовано')
    quantity = models.IntegerField()

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, null=True, related_name='vendor')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, related_name='category')

    class Meta:
        verbose_name_plural = 'Продукты'
        verbose_name = 'Продукт'

    def products_image(self):
        return mark_safe('<img src="%s" width = "50" height = "50">' % (self.image.url))

    def __str__(self):
        return self.title

    def get_percentage(self):
        new_price = ((self.old_price - self.price) / self.old_price) * 100
        return new_price


class ProductImages(models.Model):
    image = models.ImageField(upload_to='product-images', default='product.jpg')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = 'Продуктовые изображения'
        verbose_name = 'Продуктовая иконка'


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, related_name='product')
    review = models.TextField(max_length=1000)
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Отзывы'
        verbose_name = 'Отзыв'

    def __str__(self):
        return self.product.title

    def get_ratings(self):
        return self.rating


class Contact(models.Model):
    objects = models.manager.Manager()
    user = models.ForeignKey(User, verbose_name='Пользователь',
                             related_name='contacts', blank=True,
                             on_delete=models.CASCADE)

    city = models.CharField(max_length=50, verbose_name='Город')
    street = models.CharField(max_length=100, verbose_name='Улица')
    house = models.CharField(max_length=15, verbose_name='Дом', blank=True)
    structure = models.CharField(max_length=15, verbose_name='Корпус', blank=True)
    building = models.CharField(max_length=15, verbose_name='Строение', blank=True)
    apartment = models.CharField(max_length=15, verbose_name='Квартира', blank=True)
    phone = models.CharField(max_length=20, verbose_name='Телефон')

    class Meta:
        verbose_name = 'Контакты пользователя'
        verbose_name_plural = "Список контактов пользователя"

    def __str__(self):
        return f'{self.city} {self.street} {self.house}'


class Order(models.Model):
    objects = models.manager.Manager()
    user = models.ForeignKey(User, verbose_name='Пользователь',
                             related_name='user', blank=True,
                             on_delete=models.CASCADE)
    dt = models.DateTimeField(auto_now_add=True)
    state = models.CharField(verbose_name='Статус', choices=STATUS_CHOISE, max_length=15)
    contact = models.ForeignKey(Contact, verbose_name='Контакт',
                                blank=True, null=True,
                                on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Заказов'
        verbose_name_plural = "Список заказов"
        ordering = ('-dt',)

    def __str__(self):
        return str(self.dt)


class OrderItem(models.Model):
    objects = models.manager.Manager()
    order = models.ForeignKey(Order, verbose_name='Заказ', related_name='ordered_items', blank=True,
                              on_delete=models.CASCADE)

    product_name = models.ForeignKey(Product, verbose_name='Информация о продукте', related_name='ordered_items',
                                     blank=True,
                                     on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='Количество')

    class Meta:
        verbose_name = 'Заказанная позиция'
        verbose_name_plural = "Список заказанных позиций"

    def __str__(self):
        return str(self.order.id)


class Projects(models.Model):
    title = models.CharField(max_length=1000)
    description = models.CharField(max_length=10000)
    stack = models.CharField(max_length=1000)
    git = models.URLField(max_length=1000, null=True, blank=True)
    image = models.ImageField(upload_to='projects', default='project.jpg')

    class Meta:
        verbose_name_plural = 'Проекты'
        verbose_name = 'Проект'

    def project_image(self):
        return mark_safe('<img src="/media/%s" width = "50" height = "50">' % (self.image))

shop/forms.py
from string import Template

from django import forms
from .models import *


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(
        widget=forms.Textarea(
            attrs={'placeholder': 'Оставьте отзыв'}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title', 'image']

shop/views.py
from django.db.models.aggregates import Avg
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.conf import settings
from django.urls import reverse_lazy
from rest_framework.generics import ListAPIView
from rest_framework.response import Response

from .serializers import *
from rest_framework import status

from .forms import *
from .models import *

User = settings.AUTH_USER_MODEL


def projects(request):
    project = Projects.objects.all()
    context = {
        'project': project

    }
    return render(request, 'project_page_2.html', context)


def base(request):
    return render(request, 'base_page.html', )



def index(request):
    vendor = Vendor.objects.filter(available=True)
    products = Product.objects.filter(feachured=True, vendor__in=vendor, product_status="опубликовано").order_by('-id')
    context = {
        "products": products,
        'vendor': vendor,
    }

    return render(request, 'shop/index.html', context)



def product_list_view(request, title):
    category = Category.objects.get(title=title)
    products = Product.objects.filter(product_status="опубликовано", category=category)
    context = {
        'category': category,
        'products': products,

    }
    return render(request, 'shop/index.html', context)



def category_list(request):
    category = Category.objects.all().order_by('-id')
    cat_form = CategoryForm()
    context = {
        "category": category,
        'cat_form': cat_form
    }

    return render(request, 'shop/category.html', context)



def product_view(request, title):
    one_prod = Product.objects.get(title=title)
    product = Product.objects.filter(title=title)
    reviews = ProductReview.objects.filter(product=one_prod)
    average_rating = ProductReview.objects.filter(product=one_prod).aggregate(rating=Avg('rating'))
    review = ProductReviewForm()
    context = {
        'product': product,
        'reviews': reviews,
        'average_rating': average_rating,
        'review': review

    }
    return render(request, 'shop/product_2.html', context)



def add_review(request, title):
    product = Product.objects.get(title=title)
    user = request.user
    if request.method == "POST":
        form = ProductReviewForm(request.POST)
        if form.is_valid():
            review_post = ProductReview.objects.create(
                product=product,
                user=user,
                review=form.cleaned_data['review'],
                rating=form.cleaned_data['rating']
            )
            review_post.save()
            return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

    context = {
        'user': user.username,
        'review': request.POST.get('review'),
        'rating': request.POST.get('rating'),
    }
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))

    return render(request, 'shop/product.html', context)

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="shortcut icon" type="image/png" href="{% static 'icon/shortcut.png' %}"/>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Магазин</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    </head>
    <body>
        {% include 'shop/navbar.html' %}
        {% if messages %}
            {% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
            {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}




        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Учкин Семён 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

shop/templates/shop/base_2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="shortcut icon" type="image/png" href="{% static 'icon/shortcut.png' %}"/>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Сайт-портфолио</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    </head>
    <body>
        {% include 'shop/navbar_2.html' %}
        {% if messages %}
            {% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
            {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}




        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Учкин Семён 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

shop/templates/shop/category.html
{% extends 'shop/base.html' %}


{% block content %}

{% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'icon/shortcut.png' %}"/>

<head>
    <meta charset="UTF-8">
    <title>Категории продуктов</title>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>
</head>
<form action="{% url 'cart_summary' %}" class = 'd-flex'>
<!--        <button class = 'btn btn-' type="submit">-->
<!--            Корзина-->
<!--            <span class = 'badge bg=dark text-white ms-2 rounded-pill'>0</span>-->
<!--        </button>-->
</form>
<body>
    <ul>

        {% for p in category %}
        <div style = "border:3px groove;width: 200px;background-color: white;margin:1em auto;border-width:5px;border-radius: 5px;display: inline-block">

            <a href="{% url 'product_list_view' p.title %}">
                <div style = "text-align: center;">
                <img width="100" height="100" src = "{{ p.image.url }}" />
            </a>
            <br>
            <h7 class="card-text justified"><a>{{p.title}}</a></h7>
            <br>
                <h8><a>{{p.category.count}} товар{{p.category.count|pluralize:"а"}}</a></h8>
            </div>
        </div>
        {% endfor %}

        </form>
    </div>
</body>


{% endblock %}

shop/templates/shop/product.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
{% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'icon/shortcut.png' %}"/>
<body style='background-image: url(https://catherineasquithgallery.com/uploads/posts/2021-02/1613231255_86-p-fon-sine-zelenii-gradient-103.jpg);background-size: cover;'>
</body>
<head>
    <meta charset="UTF-8">
    <title>Описание товара</title>
</head>
<form action="{% url 'cart_summary' %}" class = 'd-flex'>
        <button class = 'btn btn-' type="submit">
            Корзина
            <span class = 'badge bg=dark text-white ms-2 rounded-pill'>0</span>
        </button>
</form>
<body>

    {% for p in product %}
    <div style = "border:3px groove;width: 600px;margin:1em auto;border-width:5px;border-radius: 20px;background-color: white;display: inline-block">
            <div style = "text-align: center;">
                <div style = " background-color: red">
                <h4><a>-{{p.get_percentage|floatformat:0}}%</a> </h4>
                    </div>
                <div class="sim-slider">
                    <ul class="sim-slider-list">
                        <li><img width="300" height="300" src = "{{ p.image.url }}" /></li>
                     </ul>
                  <div class="sim-slider-arrow-left"></div>
                  <div class="sim-slider-arrow-right"></div>
                  <div class="sim-slider-dots"></div>
                </div>
                    <h5><a href="{% url 'product_list_view' p.category %}">{{p.category}}</a></h5>
                <h2><a>{{p.title}}</a></h2>
                <h4><a>{{p.price}}</a> ₽</h4>
                   <h5> <strike>{{p.old_price}}₽</strike></h5>
                <h5> Поставщик: <a>{{p.vendor}}</a></h5>
                <h5> Описание товара: <a>{{p.description}}</a></h5>

                <h4><a>Количество отзывов: {{reviews.count}}</a></h4>
                <h4><a>Рейтинг: {{average_rating.rating|floatformat:1}} из 5</a></h4>

                    {% for r in reviews %}
                <div style = "border:3px groove;width: 600px;;border-width:3px;border-radius: 20px;background-color: #FFFFE0;display: inline-block">
                        <h5><a>{{r.user.username|title}}</a></h5>
                        <h4><a>{{r.review}}</a></h4>
                        <h4><a>{{r.get_rating_display}}</a></h4>
                        <h6><a>{{r.date}}</a></h6>

                        </div>{% endfor %}
                {% if request.user.is_authenticated %}
                <form action="{% url 'add_review' p.title %}" method="POST">
                    {{ review.review }}<br>
                    {{ review.rating }}
                    {% csrf_token %}
                    <a href="{% url 'add_review' p.title %}" >
                        <input type="submit" class="btn btn-outline-primary text-dark btn-block text-black"  style="width:190px;height:35px;border-radius: 10px" value="отправить" />
                        </a>
                    </form>
            <button type="button"  value="{{ p.id }}" id ="add-cart">Добавить в корзину</button>
            </div>
        </div>{% else %}
    <h4><a>Авторизуйтесь - для отправки комментария</a></h4>
    {% endif %}


        <form action="{%  url 'category' %}">
                    <input type="submit" class="btn btn-outline-primary text-dark btn-block text-black" style="width:190px;height:35px;border-radius: 10px" value="Перейти к категориям" />
                </form>
        <form action="{%  url 'base' %}">
                    <input type="submit" class="btn btn-outline-primary text-dark btn-block text-black" style="width:190px;height:35px;border-radius: 10px" value="В главное меню" />
                </form>

    {% endfor %}


<script src="https://code.jquery.com/jquery-3.7.1.min.js"
integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
crossorigin="anonymous">
$(document).on('click', '#add-cart', function(e) {
    e.preventDefault();
    $.ajax({
        type: 'POST',
        url: '{% url 'cart_add' %}',
        data: {
            product_id: $('#add-cart').val(),
            csrfmiddlewaretoken : '{{  csrf_token }}',
            action: 'post',
        },

        success: function(json){
            console.log(json)
        },

        error:  function(xhr, errmsg, err){

        }

    });
})
</script>

</body>
</html>
<style>
img {
  width: 100%; !important;
}

.sim-slider {
  max-width: 1000px;
  min-width: 320px;
  margin: 20px auto;
  padding: 30px 50px;
  border: 1px solid #ccd;
  background-color: white;
}

/* General styles */
.sim-slider {
  position: relative;
}

.sim-slider-list {
  margin: 0;
  padding: 0;
  list-style-type: none;
  position: relative;
}

.sim-slider-element {
  width: 100%;
  transition: opacity 1s ease-in;
  opacity: 0;
  position: absolute;
  z-index: 2;
  left: 0;
  top: 0;
  display: block;
}

/* Navigation item styles */
div.sim-slider-arrow-left,
div.sim-slider-arrow-right {
  width: 22px;
  height: 40px;
  position: absolute;
  cursor: pointer;
  opacity: 0.6;
  z-index: 4;
}

div.sim-slider-arrow-left {
  left: 10px;
  top: 40%;
  display: block;
  background: url("http://pvbk.spb.ru/inc/slider/sim-files/sim-arrow-left.png") no-repeat;
}

div.sim-slider-arrow-right {
  right: 10px;
  top: 40%;
  display: block;
  background: url("http://pvbk.spb.ru/inc/slider/sim-files/sim-arrow-right.png") no-repeat;
}

div.sim-slider-arrow-left:hover {
  opacity: 1.0;
}

div.sim-slider-arrow-right:hover {
  opacity: 1.0;
}

div.sim-slider-dots {
  width: 100%;
  height: auto;
  position: absolute;
  left: 0;
  bottom: 0;
  z-index: 3;
  text-align: center;
}

span.sim-dot {
  width: 10px;
  height: 10px;
  margin: 5px 7px;
  padding: 0;
  display: inline-block;
  background-color: #BBB;
  border-radius: 5px;
  cursor: pointer;
}

</style>

shop/templates/shop/product_2.html
{% extends 'shop/base.html' %}
{% block content %}



<div class="container">
<br/>

{% for p in product %}
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{ p.image.url }}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">

        <center>
        <h5 class="card-title">{{ p.name }}</h5>
        <br/>
        <p class="card-text justified">{{ p.description }}</p>


        <div class="d-flex justify-content-center small text-warning mb-2">
                <div class="bi-star-fill"></div>
                Скидка {{p.get_percentage|floatformat:0}}%
                <div class="bi-star-fill"></div>
                </div>

                <strike>
                {{ p.old_price }}₽
                </strike>
                &nbsp;





            {{ p.price }}₽

<p class="card-text justified"><a>Количество отзывов: {{reviews.count}}</a></p>
                <p class="card-text justified"><a>Рейтинг: {{average_rating.rating|floatformat:1}} из 5</a></p>
            <br/><br/>
<div class="row justify-content-center">
    <div class="col-md-2">Количество:</div>
                <div class="col-md-2">
                <select class="form-select form-select-sm" id="qty-cart">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                </select>
                </div>
            </div>
            <br/><br/>
        <a href="{% url 'category'%}" class="btn btn-secondary">В меню</a>
        <button type="button" value="{{ p.id }}" class="btn btn-secondary" id="add-cart">Добавить в корзину</button>
            <br><br><br>
            {% for r in reviews %}
                <div style = "border:3px groove;width: 300px;border-width:2px;border-radius: 5px;background-color: white;display: inline-block">
                        <p><a>{{r.user.username|title}}</a></p>
                        <p class = 'short'><a>{{r.review}}</a></p>
                        <p class = 'short'><a>{{r.get_rating_display}}</a></p>
                        <p class = 'short' ><a><font size="1">{{r.date}}</font></a></p>

                        </div>
            {% endfor %}
                {% if request.user.is_authenticated %}
                <form action="{% url 'add_review' p.title %}" method="POST">
                    {{ review.review }}<br>
                    {{ review.rating }}
                    {% csrf_token %}
                    <a href="{% url 'add_review' p.title %}" >
                        <input type="submit" class="btn btn-secondary"  style="width:190px;height:35px;border-radius: 10px" value="Отправить" />
                        </a>
                    </form>
            </div>{% else %}
    <p class="row justify-content-center"><a>Авторизуйтесь - для отправки комментария</a></p>
    {% endif %}
    {% endfor %}
    </center>
      </div>
    </div>
  </div>
</div>
</div>

<script>
// Check if button pressed
$(document).on('click', '#add-cart', function(e){
    e.preventDefault();
    $.ajax({
        type: 'POST',
        url: '{% url 'cart_add' %}',
        data: {
    product_id: $('#add-cart').val(),
    product_qty: $('#qty-cart option:selected').text(),
    csrfmiddlewaretoken: '{{ csrf_token }}',
    action: 'post'
        },

        success: function(json){
            //console.log(json)
            document.getElementById("cart_quantity").textContent = json.qty
        },

        error: function(xhr, errmsg, err){

        }


    });



})
</script>

<style>
    .short
    {
    line-height: 7px;

}
</style>
{% endblock %}